version: '3.0'

services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./library_back/.env
    ports:
      - 5432:5432

  library_back:
    container_name: library_back
    build:
      context: library_back
      dockerfile: Dockerfile
    command: python manage.py runserver
    ports:
      - 8000:8000
    volumes:
      - .:/django-app
    depends_on:
      - database


    