version: '3.0'

services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - ./var/lib/postgresql/data
    env_file:
      - ./library_back/.env
    networks:
      - backend

  library_back:
    container_name: library_back
    build:
      context: ./library_back
      dockerfile: Dockerfile
    command: bash -c " 
              python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./library_back:/library_back
    depends_on:
      - database
    networks:
      - backend

  library_front:
    container_name: library_front
    build:
      context: ./library_front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/library_front
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge