version: "3.0"

services:
  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - database:/var/lib/postgresql/data/
    restart: always

  librar_back-test:
    build: .
    command:
      - /bin/bash
      - -c
      - python manage.py makemigrations && python manage.py migrate && python -m manage test
    volumes:
      - .:/library_back
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  database: