name: CD

on:
  workflow_run:
    workflows: CI
    types:
      - completed

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: SetUp Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Backend
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:library_back"
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gces-2022-1:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./library_front
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gces-2022-1:latest