name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Criando varivael de ambiente (.env)
        run: |
          echo POSTGRES_DB=library_db >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOST=database >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env
      - name: Build backend e frontend
        working-directory: ./
        run: docker-compose up -d

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
    
  #     - name: Realizacao dos testes do backend
  #       working-directory: ./library_back/books/
  #       run: docker-compose run app rails db:reset
  #     - name: Run tests
  #       working-directory: ./aplicacao
  #       run: docker-compose run app rspec
    
  # lint: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install and run lint
  #       working-directory: ./
  #       run: docker-compose run app bash -c "gem install rubocop; rubocop --fail-level F"